name: Build ESP32-J2534 DLL (Win32)

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build-dll:
    runs-on: windows-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Configura CMake (Win32 / Release)
        run: |
          cmake ./dll `
            -G "Visual Studio 17 2022" `
            -A Win32 `
            -B build_release

      - name: Compila a DLL
        run: |
          cmake --build build_release --config Release

      - name: Upload DLL
        uses: actions/upload-artifact@v4
        with:
          name: esp32_j2534_V6_github_rev01
          path: |
            build_release/Release/esp32_j2534.dll
            firmware/
            protocol.h
            config.ini
            register_j2534.reg
          retention-days: 30
